import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
test('operational migration: atomic reminders, provenance, review and communication with RLS',async()=>{
  const db=new PGlite();
  try {
    await db.exec(`create role anon;create role authenticated;create schema auth;
      create table auth.users(id uuid primary key,raw_user_meta_data jsonb);
      create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
      grant usage on schema public,auth to authenticated,anon;
      grant execute on function auth.uid() to authenticated,anon;`);
    for(const name of ['001_panel.sql','002_load_operations.sql','002_load_operations.sql'])
      await db.exec(await readFile(new URL('../../supabase/migrations/'+name,import.meta.url),'utf8'));
    const csr='00000000-0000-0000-0000-000000000001', manager='00000000-0000-0000-0000-000000000002';
    await db.exec(`insert into auth.users values ('${csr}','{}'),('${manager}','{}');update profiles set role='csr' where id='${csr}';update profiles set role='manager' where id='${manager}';`);
    const asUser=async id=>{await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);await db.exec('set role authenticated');};
    const load=async()=> (await db.query("select *,updated_at::text as version from loads where load='OP-1'")).rows[0];
    await asUser(csr);
    await assert.rejects(db.exec("insert into loads(load,status) values ('INVALID','Patio permisionario')"),/recordatorio/);
    await assert.rejects(db.exec("insert into loads(load,tracking_link) values ('INVALID','javascript:alert(1)')"),/http/);
    await db.exec("insert into loads(load,status,truck) values ('OP-1','Cargando','TR-1')");
    assert.equal((await load()).truck_source,'MANUAL');
    assert.equal((await load()).truck_manual_by,csr);
    await assert.rejects(db.exec("update loads set next_review_at='2026-10-10T10:00' where load='OP-1'"),/zona horaria/);
    await db.exec("update loads set status='En transito' where load='OP-1'");
    let row=await load();
    assert.equal(row.client_notify_pending,'true');
    assert.ok(Date.parse(row.recordatorio_fecha)>Date.now()+2.9*3600000);
    const oldVersion=row.version;
    await db.exec("update loads set delivery_appt='2026-10-10T12:00:00Z' where load='OP-1'");
    assert.match((await load()).client_notify_reason,/estatus.*cita de entrega/);
    await assert.rejects(db.query('select * from confirm_client_notice($1,$2,$3,$4)',['OP-1',oldVersion,'WhatsApp','Cambio de cita']),/cambió/);
    row=await load();
    await db.query('select * from confirm_client_notice($1,$2,$3,$4)',['OP-1',row.version,'WhatsApp','Cambio de cita']);
    row=await load();
    assert.equal(row.client_notify_pending,'false');assert.equal(row.client_notify_reason,'');
    assert.equal(row.client_notified_by,csr);
    const log=(await db.query("select * from communications where event_type='NOTIFICADO'")).rows[0];
    assert.equal(log.channel,'WhatsApp');assert.equal(log.notice_type,'Cambio de cita');assert.equal(log.actor,csr);
    await db.exec("update loads set recordatorio_fecha='2026-01-01T00:00:00Z' where load='OP-1'");
    await db.exec("insert into comments(load,body) values ('OP-1','Revisé el seguimiento')");
    assert.ok(Date.parse((await load()).recordatorio_fecha)>Date.now()+2.9*3600000);
    await db.exec("update loads set cruce_usa_fecha='2026-10-10T09:00:00Z',cruce_confirmado='true' where load='OP-1'");
    assert.equal((await load()).cruce_confirmado,'');
    await db.exec("update loads set cruce_confirmado='true' where load='OP-1'");
    assert.equal((await load()).cruce_confirmado,'true');
    await db.exec("update loads set status='Descompuesta',recordatorio_fecha='2026-10-10T15:00:00Z' where load='OP-1'");
    await db.exec("update loads set status='Cargando' where load='OP-1'");
    assert.equal((await load()).recordatorio_fecha,'');
    await db.exec("update loads set next_review_at='2026-10-10T15:00:00Z',next_review_note='Llamar' where load='OP-1'");
    row=await load();assert.equal(row.next_review_by,csr);
    await db.query('select * from review_load($1,$2)',['OP-1',row.version]);
    row=await load();assert.equal(row.next_review_at,'');assert.equal(row.next_review_note,'');
    await assert.rejects(db.exec("insert into communications(load,event_type) values ('OP-1','NOTIFICADO')"));
    await asUser(manager);
    assert.ok((await db.query('select * from communications')).rows.length>0);
    row=await load();
    await assert.rejects(db.query('select * from review_load($1,$2)',['OP-1',row.version]),/Sin permiso/);
    await assert.rejects(db.query('select * from confirm_client_notice($1,$2,$3,$4)',['OP-1',row.version,'Correo','Estado']),/Sin permiso/);
    await db.exec('reset role;set role anon');
    await assert.rejects(db.query('select * from communications'));
    await assert.rejects(db.query("select * from review_load('OP-1',now())"));
  } finally {await db.close();}
});
